server:
  port: 8080

spring:
  application:
    name: GmbhStrings
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/h2test;AUTO_SERVER=TRUE
    username: sa
    password:
    tomcat:
      max-active: 10
      max-wait: 3000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: DEBUG

