DROP TABLE IF EXISTS GMBH_STRING;

CREATE TABLE GMBH_STRING (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  value VARCHAR(32766),
  length SMALLINT NOT NULL
);

CREATE INDEX IF NOT EXISTS GMBH_STRING_VALUE ON GMBH_STRING(value);